/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekt_kino;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Lenovo
 */
public class EkranLogowania extends javax.swing.JFrame {

    ArrayList<LoginData> Pass_list;
    GUI1 mainGUI;
    
    
    public EkranLogowania(GUI1 m) {
        initComponents();
        mainGUI = m;
        this.Pass_list = new ArrayList<>();
        this.readLoginData();
    }
    
    class LoginData {
        String login;
        String password;
        
        public LoginData(String l, String p){
            this.login = l;
            this.password = p;
        }
        
        String getLogin(){
            return this.login;
        }
        
        String getPassword(){
            return this.password;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextPas = new javax.swing.JPasswordField();
        jTextLog = new javax.swing.JTextField();
        jButLoguj = new javax.swing.JButton();
        jButCofnij = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelLogin.setText("Login:");

        jLabelPassword.setText("Haslo:");

        jTextPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPasActionPerformed(evt);
            }
        });

        jTextLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLogActionPerformed(evt);
            }
        });

        jButLoguj.setText("Zaloguj");
        jButLoguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButLogujActionPerformed(evt);
            }
        });

        jButCofnij.setText("Cofnij");
        jButCofnij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCofnijActionPerformed(evt);
            }
        });

        jLabelMessage.setText("Zaloguj się");
        jLabelMessage.setHorizontalAlignment(JLabel.CENTER);
        jLabelMessage.setVerticalAlignment(JLabel.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButCofnij)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButLoguj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextLog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabelMessage)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jTextLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jTextPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButLoguj)
                .addGap(53, 53, 53)
                .addComponent(jButCofnij)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLogActionPerformed

    private void jTextPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPasActionPerformed

    //Obsluga przycisku "Loguj" sprawdzenie czy wpisane dane są zgoden z danymi wczytanymi z pliku
    private void jButLogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButLogujActionPerformed
        String user = jTextLog.getText();
        String password = jTextPas.getText();
        boolean isLoged = false;
        
        for(LoginData data : Pass_list){
            System.out.println(data.getLogin() + " " + data.getPassword());
            if( user.equals(data.login) && password.equals(data.password)){
                isLoged = true;
                break;
            }
        }
        
        if(isLoged){
                jLabelMessage.setText("Zalogowano");
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (InterruptedException ex) {
                Logger.getLogger(EkranLogowania.class.getName()).log(Level.SEVERE, null, ex);
            }
                this.setVisible(false);
                mainGUI.zaloguj(user);
                mainGUI.setVisible(true);
            
            }
            else{
                jLabelMessage.setText("Niepoprawny login lub hasło");
                
            } 
        jTextLog.setText("");
        jTextPas.setText("");
    }//GEN-LAST:event_jButLogujActionPerformed

    //Obsluga akcji przycisku cofnij
    private void jButCofnijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCofnijActionPerformed
        this.setVisible(false);
        mainGUI.setVisible(true);
    }//GEN-LAST:event_jButCofnijActionPerformed
    
    private void readLoginData() {
        
        File file = new File("dane_logowania.txt");
       String log, pas;
        
        try (Scanner inputFile = new Scanner(file)) {
        inputFile.useDelimiter(" |\\R");
           
        while (inputFile.hasNext()) {
            log = inputFile.next();
            pas = inputFile.next();
            
            LoginData Passy = new LoginData(log, pas);
            this.Pass_list.add(Passy);
            }} 
        catch(FileNotFoundException e) {
            System.out.println("Check file");
                }
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButCofnij;
    private javax.swing.JButton jButLoguj;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JTextField jTextLog;
    private javax.swing.JPasswordField jTextPas;
    // End of variables declaration//GEN-END:variables
}
